### ISSUE TITLE
台服鵝毛大雪 isQuestFinish 誤判

### ISSUE THREAD

**Issue by hephooey** [Cooper6334/fgoautoscript#1]
這幾天用大大的腳本刷聖誕的鵝毛大雪，大概是因爲背景一片白茫茫的關係，在 Wave 3 的時候 isQuestFinish 經常把進行中的動畫判斷成申請好友的頁面，就是 template matching 到了 FinishStage1.png。我現在的做法是略微改變代碼當 match 到 Stage1 的時候等 5 秒再判斷一次。跑了幾場似乎很穩定，就是效率稍稍有點折扣。用的是月神模擬器，Wave 3 的時候場上依次是殺師匠，小黑和二世，沒有在手機上測試過。

**Comment by hephooey** [comment]
剛發現新版本已經 fix 了。

**Comment by Cooper6334** [comment]
還有我現在都是在這邊更新
https://github.com/Cooper6334/robotmon-scripts

這裡就沒在動了

**Comment by hephooey** [comment]
我一開始也是打算去那邊寫 issue 的，不過 robotmon-scripts 的 repo 沒有開啓 issue 的 feature。似乎需要在 fork 之後手動 enable
